[package]
name = "day24"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eqsolver = "0.1.2"
nalgebra = "0.32.3"
rust_decimal = "1.33.1"
rust_decimal_macros = "1.33.1"
